steps:
  - name: alpine
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
    id: branch name
    entrypoint: sh
  - name: 'hashicorp/terraform:1.1.3'
    args:
      - '-c'
      - |
          terraform init
    id: tf init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.1.3'
    args:
      - '-c'
      - |
          terraform plan
    id: tf plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.1.3'
    args:
      - '-c'
      - |
          terraform apply -auto-approve
    id: tf apply
    entrypoint: sh
