steps:
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
          terraform init
    id: tf init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
          terraform plan
    id: tf plan
    entrypoint: sh
  - name: 'hashicorp/terraform:1.0.0'
    args:
      - '-c'
      - |
          terraform apply -auto-approve
    id: tf apply
    entrypoint: sh
