steps:
  - name: alpine
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
    id: branch name
    entrypoint: sh
  - name: 'hashicorp/terraform:1.1.3'
    args:
      - '-c'
      - |
        terraform init
    id: tf init
    entrypoint: sh
  - name: 'hashicorp/terraform:1.1.3'
    args:
      - '-c'
      - |
        terraform destroy -auto-approve
    id: tf destroy
    entrypoint: sh